// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vehiclesApi.Data;

#nullable disable

namespace vehiclesApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230528064923_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("vehiclesApi.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<Guid?>("VehicleTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("98474b8e-d713-401e-8aee-acb7353f97bb"),
                            Available = true,
                            Description = "AUDI Q5 ELITE S TRONIC QUATTRO 2.0T STD/AUT 5PTAS MOD 2015.",
                            Price = 300000f,
                            VehicleTypeId = new Guid("90d10994-3bdd-4ca2-a178-6a35fd653c59")
                        },
                        new
                        {
                            Id = new Guid("bfe902af-3cf0-4a1c-8a83-66be60b028ba"),
                            Available = true,
                            Description = "NISSAN INFINITI M37 PREMIUM VP QC DVD GPS RA-18 AU MOD 2017. ",
                            Price = 190000f,
                            VehicleTypeId = new Guid("90d10994-3bdd-4ca2-a178-6a35fd653c59")
                        },
                        new
                        {
                            Id = new Guid("bd9f66d9-38db-40dd-bf52-cab3f73ed926"),
                            Available = true,
                            Description = "Vento Screamer Sportivo MOD 2024.",
                            Price = 48999f,
                            VehicleTypeId = new Guid("6ebc3dbe-2e7b-4132-8c33-e089d47694cd")
                        },
                        new
                        {
                            Id = new Guid("9d42967b-e48b-4b38-ba76-5cb12d8b18cb"),
                            Available = true,
                            Description = "Harley Davidson Street 750 Black Motorcycle Model Bike 1/12 by Maisto MOD 2015.",
                            Price = 355959f,
                            VehicleTypeId = new Guid("6ebc3dbe-2e7b-4132-8c33-e089d47694cd")
                        },
                        new
                        {
                            Id = new Guid("2d099aff-a8ab-4a5c-9551-6fc74952b4e8"),
                            Available = true,
                            Description = "Suzuki Grand Vitara GLX MOD 2019.",
                            Price = 480000f,
                            VehicleTypeId = new Guid("150c81c6-2458-466e-907a-2df11325e2b8")
                        });
                });

            modelBuilder.Entity("vehiclesApi.Models.VehicleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehiclesType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90d10994-3bdd-4ca2-a178-6a35fd653c59"),
                            Name = "Automóviles"
                        },
                        new
                        {
                            Id = new Guid("6ebc3dbe-2e7b-4132-8c33-e089d47694cd"),
                            Name = "Motocicletas"
                        },
                        new
                        {
                            Id = new Guid("150c81c6-2458-466e-907a-2df11325e2b8"),
                            Name = "Camionetas"
                        });
                });

            modelBuilder.Entity("vehiclesApi.Models.Vehicle", b =>
                {
                    b.HasOne("vehiclesApi.Models.VehicleType", "VehicleType")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleTypeId");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("vehiclesApi.Models.VehicleType", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
